/**
 * renderAmbient.ts — Offline browser renderer for WAV export.
 *
 * Fixes applied:
 *   C1: Drum events scheduled at beatTime + (subBeatIndex * sixteenthSec)
 *   C2: Noise buffer generated by consuming from state.rngState directly
 *       (advances main stream by ~22k calls, matching original engine.ts order)
 *   C4: 600ms harmonic slew applied via OfflineAudioContext time scheduling
 *   W3: Remove duplicated scene interpolation — accumulate beat time using
 *       actual per-beat BPM from nextState after each getMusicalEvents call
 *   ✅ FIX (NOISE_BUFFER_SAMPLES): use shared constant
 *   ✅ FIX (continue in-progress live slew): seed offline slew from startState
 *   ✅ FIX (params mutation): clone params to avoid mutating caller
 *   ✅ FIX (beat-loop cap): use minimum possible BPM across scenes to prevent truncation
 *
 * Layered additions (swing / sidechain / beatless drone latch reset):
 *   ✅ ADD (scheduling helpers): Imports getSubBeatEventTime() and
 *       getSidechainDuckShape() from ./scheduling. The single offline
 *       subBeatIndex → eventTime conversion now goes through
 *       getSubBeatEventTime() so swing is applied uniformly to every odd
 *       sixteenth — matching LiveEngine's swing behaviour exactly so live
 *       and offline renders stay sample-aligned for the same params.
 *   ✅ ADD (tonal-bus sidechain duck): Kick events trigger
 *       scheduleSidechain() which ducks `gain` (the tonal bus) — NOT `out`
 *       (the master). Ducking `out` would also duck the drum bus (which
 *       joins at `out`), silencing the kick that triggered the sidechain.
 *       Ducking `gain` leaves the drum bus untouched, which is the desired
 *       classic sidechain effect.
 *   ✅ ADD (droneLayersStarted reset): When startState is provided, the
 *       clone resets `droneLayersStarted = false` so an offline render
 *       seeded from a live state snapshot re-fires the drone oscillators.
 *       Without this reset, a snapshot taken after the live engine had
 *       already latched the drone would render with zero drone events.
 *   ✅ ADD (TONAL_BUS_GAIN constant): Named so the constructor init and
 *       scheduleSidechain() share the same source of truth. Mirrors
 *       LiveEngine's TONAL_BUS_GAIN — keeping the two in lockstep is the
 *       easiest way to keep live and offline renders perceptually matched.
 *   ✅ ADD (drone layer re-anchor): scheduleDrone() now mirrors LiveEngine's
 *       per-beat parameter updates (frequency, detune, pan, filter, FM
 *       modulator tracking) instead of the old first-write-wins behaviour
 *       that silently dropped updates after the layer's first beat. It
 *       re-anchors the gain envelope on every update via cancelAndHold(),
 *       tracking the full piecewise curve (exponential approach + sustain +
 *       release) in DroneCurveState so the Firefox fallback anchors to the
 *       true automated value at the re-anchor time.
 */

import {
  type EngineParams,
  type EngineState,
  type MusicalEvent,
  type TimbreMode,
  getMusicalEvents,
  createInitialState,
  initializeBell,
  initializeSampleLane,
  mulberry32Next,
  getEffectiveSceneParams,
  getScenePackScenes,
  MAX_DRONE_LAYERS,
  DRONE_FADE_SEC,
  NOISE_BUFFER_SAMPLES,
} from "./musicalLogic";
import {
  decodeSampleBank,
  getDecodedSampleBuffer,
  scheduleSamplePlayback,
  type DecodedSampleBank,
} from "./sampleBank";
import {
  cancelAndHold,
  evaluateDroneEnvelope,
  getSidechainDuckShape,
  getSubBeatEventTime,
  PAN_DRIFT_TIME_CONSTANT_SEC,
  resolveToneEnvelope,
  TONAL_BUS_GAIN,
} from "./scheduling";

const FM_MOD_RATIO = 1.5;
const FM_INDEX = 1.8;

const SAMPLE_FADE_SEC = 0.01;
const DRONE_PAN_TIME_CONSTANT_SEC = 0.25;
const DRONE_FILTER_CUTOFF_HZ = 3600;
const DRONE_PARAMETER_TIME_CONSTANT_SEC = 0.5;
const DRONE_FADE_TARGET_DIVISOR = 3;
const DRONE_FILTER_LFO_DEPTH_HZ = 800;
const DRONE_TAIL_SEC = 0.05;
const DRONE_RELEASE_SILENCE_GAIN = 0.0001;
// PAN_DRIFT_TIME_CONSTANT_SEC is imported from ./scheduling (single source
// of truth shared with LiveEngine.tick()).
// CodeRabbit nitpick: DRONE_FADE_SEC now imported from musicalLogic.ts
// (single source of truth shared with LiveEngine).
// TONAL_BUS_GAIN is imported from ./scheduling (single source of truth
// shared with LiveEngine) — see scheduling.ts for why it lives there.

export interface RenderProgress {
  phase: "preparing" | "scheduling" | "rendering" | "encoding";
  percent: number;
}

// Tracks the piecewise gain-automation curve for one drone layer so the
// Firefox cancelAndHold fallback can anchor to the true automated value at a
// re-anchor time instead of a stale stored target. Fields are populated by
// scheduleDrone() every beat and read back by evaluateDroneEnvelope().
interface DroneCurveState {
  fromValue: number;
  toValue: number;
  startTime: number;
  timeConstant: number;
  sustainTime: number | null;
  sustainValue: number;
  releaseEndTime: number;
  releaseTarget: number;
}

// Per-render sidechain automation tracker. Mirrors DroneCurveState: records
// the attack and release segments scheduled by the most recent kick so the
// next overlapping kick can interpolate the true mid-ramp value. Created
// inside renderAmbient() and threaded through to scheduleSidechain() so two
// concurrent renders cannot interleave writes on shared module state.
// ponytail: current UI flow prevents overlapping renders, so this is a
// correctness cleanup for a not-yet-reachable race, not a fix for a live
// incident; upgrading means the UI actually permitting parallel exports.
interface SidechainTracker {
  attackStartT: number;
  attackStartV: number;
  attackEndT: number;
  attackEndV: number;
  releaseEndT: number;
  releaseEndV: number;
}

export async function renderAmbient(
  params: EngineParams,
  durationSeconds: number,
  startState?: EngineState,
  onProgress?: (progress: RenderProgress) => void,
): Promise<AudioBuffer> {
  // Clone params to avoid mutating caller's object.
  const effectiveParams: EngineParams = { ...params };
  const SAMPLE_RATE = 44100;
  const effectiveBpm = effectiveParams.bpm || 72;
  const PRE_ROLL_SECONDS = 4 * (60 / effectiveBpm) * 4; // 4 bars

  // Over-allocate 10% — we trim to exact duration after rendering
  const totalSecondsEstimate = (PRE_ROLL_SECONDS + durationSeconds) * 1.1;
  const totalSamples = Math.ceil(SAMPLE_RATE * totalSecondsEstimate);

  onProgress?.({ phase: "preparing", percent: 5 });

  const offlineCtx = new OfflineAudioContext(2, totalSamples, SAMPLE_RATE);
  const sampleBuffers = await decodeSampleBank(
    offlineCtx,
    effectiveParams.sampleBank,
  );

  // ── Audio graph (identical to LiveEngine) ──
  const gain = offlineCtx.createGain();
  const delay = offlineCtx.createDelay(2.0);
  const fb = offlineCtx.createGain();
  const filter = offlineCtx.createBiquadFilter();
  const out = offlineCtx.createGain();

  // ✅ ADD (TONAL_BUS_GAIN): named constant instead of the magic 0.3.
  gain.gain.value = TONAL_BUS_GAIN;
  delay.delayTime.value = 0.3 + 0.4 * (effectiveParams.mix || 0.4);
  fb.gain.value = 0.2 + 0.5 * (effectiveParams.mix || 0.4);
  filter.type = "lowpass";
  filter.frequency.value = 5000 + (effectiveParams.mix || 0.4) * 4000;
  filter.Q.value = 1.0;

  gain.connect(filter);
  filter.connect(delay);
  delay.connect(fb);
  fb.connect(delay);
  delay.connect(out);
  filter.connect(out);
  out.connect(offlineCtx.destination);

  const drumBus = offlineCtx.createGain();
  const drumCompressor = offlineCtx.createDynamicsCompressor();
  drumCompressor.threshold.value = -20;
  drumCompressor.ratio.value = 3;
  drumCompressor.attack.value = 0.003;
  drumCompressor.release.value = 0.25;
  drumBus.connect(drumCompressor);
  drumCompressor.connect(out);

  // FIX W3: Persistent panners in offline context too
  const padPanL = offlineCtx.createStereoPanner();
  const padPanR = offlineCtx.createStereoPanner();
  const bellPan = offlineCtx.createStereoPanner();
  padPanL.pan.value = 0;
  padPanR.pan.value = 0;
  bellPan.pan.value = 0;
  padPanL.connect(gain);
  padPanR.connect(gain);
  bellPan.connect(gain);

  // ponytail: fixed 8-layer drone cap; raising it later requires increasing
  // MAX_DRONE_LAYERS and preallocating matching persistent nodes here/live.
  const dronePans: StereoPannerNode[] = [];
  const droneGains: GainNode[] = [];
  const droneFilters: BiquadFilterNode[] = [];
  const droneOscs: Array<OscillatorNode | null> = [];
  const droneModOscs: Array<OscillatorNode | null> = [];
  const droneCurves: Array<DroneCurveState | null> = [];
  const scheduledDroneLayers = new Set<number>();
  for (let i = 0; i < MAX_DRONE_LAYERS; i++) {
    const pan = offlineCtx.createStereoPanner();
    const g = offlineCtx.createGain();
    const droneFilter = offlineCtx.createBiquadFilter();
    pan.pan.value = 0;
    g.gain.value = 0;
    droneFilter.type = "lowpass";
    droneFilter.frequency.value = 3600;
    droneFilter.Q.value = 0.7;
    droneFilter.connect(g);
    g.connect(pan);
    pan.connect(gain);
    dronePans.push(pan);
    droneGains.push(g);
    droneFilters.push(droneFilter);
    droneOscs.push(null);
    droneModOscs.push(null);
    droneCurves.push(null);
  }

  onProgress?.({ phase: "scheduling", percent: 10 });

  // ── RNG init order matches original engine.ts constructor exactly ──
  let state: EngineState;
  let noiseBuffer: AudioBuffer;

  if (startState) {
    // ✅ ADD (droneLayersStarted reset): when seeding from a live state
    // snapshot, reset the latch so the offline render re-fires the drone
    // oscillators. A snapshot taken after the live engine had already
    // latched droneLayersStarted=true would otherwise render with zero
    // drone events in beatless mode.
    state = { ...startState, droneLayersStarted: false };
    noiseBuffer = createNoiseBufferFromSnapshot(
      offlineCtx,
      createInitialState(effectiveParams).rngState,
    );
  } else {
    state = createInitialState(effectiveParams);
    noiseBuffer = createNoiseBufferFromState(offlineCtx, state); // advances ~22k in main stream
    state = initializeBell(state); // advances 1 in main stream
    state = initializeSampleLane(state, effectiveParams);
  }

  // FIX C4: Harmonic slew tracking for offline context
  let slewStartHz: number | null = null;
  let slewEndHz: number | null = null;
  let slewStartTime: number | null = null;
  let slewEndTime: number | null = null;
  const SLEW_DURATION = 0.6;

  if (startState && state.currentRootHz !== state.targetRootHz) {
    slewStartHz = state.currentRootHz;
    slewEndHz = state.targetRootHz;
    slewStartTime = 0;
    slewEndTime = SLEW_DURATION;
  }

  // ── FIX W3 + beat timing ──
  let currentTime = 0;
  const targetEndTime = PRE_ROLL_SECONDS + durationSeconds;

  // ✅ FIX: Use the minimum possible BPM to calculate maxBeats. If scenes
  // increase the BPM during export, we need MORE beats than the starting
  // BPM suggests. Using the minimum BPM (from the scene pack or params) gives us
  // the most conservative beat count, preventing truncation.
  const minBpm = Math.min(
    effectiveBpm,
    ...getScenePackScenes(effectiveParams).map((s) => s.bpm),
  );
  const maxBeats = Math.ceil(totalSecondsEstimate * (minBpm / 60)) + 100; // +100 safety margin

  let beatIndex = 0;

  // Per-render sidechain tracker (see SidechainTracker ponytail above).
  const sidechainTracker: SidechainTracker = {
    attackStartT: 0,
    attackStartV: TONAL_BUS_GAIN,
    attackEndT: 0,
    attackEndV: TONAL_BUS_GAIN,
    releaseEndT: 0,
    releaseEndV: TONAL_BUS_GAIN,
  };

  while (currentTime < targetEndTime && beatIndex < maxBeats) {
    const slewedRootHz = getSlewedHz(
      currentTime,
      state.currentRootHz,
      slewStartHz,
      slewEndHz,
      slewStartTime,
      slewEndTime,
      SLEW_DURATION,
    );
    state = { ...state, currentRootHz: slewedRootHz };

    const prevTargetRootHz = state.targetRootHz;

    // ✅ FIX: Use effectiveParams (cloned) to avoid mutating original.
    const preBeatParams = getEffectiveSceneParams(state, effectiveParams);
    const beatSec = 60 / preBeatParams.bpm;
    effectiveParams.bpm = preBeatParams.bpm;
    const sceneMix = preBeatParams.mix;
    const sixteenthSec = beatSec / 4;

    const { events, nextState } = getMusicalEvents(
      state.beat,
      { ...state },
      effectiveParams,
    );
    state = nextState;

    if (state.targetRootHz !== prevTargetRootHz) {
      slewStartHz = slewedRootHz;
      slewEndHz = state.targetRootHz;
      slewStartTime = currentTime;
      slewEndTime = currentTime + SLEW_DURATION;
    }

    const panValue = Math.sin(state.panDriftPhase) * 0.1;
    padPanL.pan.setTargetAtTime(
      -panValue,
      currentTime,
      PAN_DRIFT_TIME_CONSTANT_SEC,
    );
    padPanR.pan.setTargetAtTime(
      panValue,
      currentTime,
      PAN_DRIFT_TIME_CONSTANT_SEC,
    );
    bellPan.pan.setTargetAtTime(
      Math.sin(state.panDriftPhase * 1.3) * 0.15,
      currentTime,
      PAN_DRIFT_TIME_CONSTANT_SEC,
    );

    delay.delayTime.setTargetAtTime(0.3 + 0.4 * sceneMix, currentTime, 0.1);
    fb.gain.setTargetAtTime(0.2 + 0.5 * sceneMix, currentTime, 0.1);
    filter.frequency.setValueAtTime(5000 + sceneMix * 4000, currentTime);

    for (const event of events) {
      // ✅ ADD (swing): single offline subBeatIndex → eventTime conversion
      // now goes through getSubBeatEventTime() so params.swing is applied
      // to every odd sixteenth, matching LiveEngine exactly. Tonal events
      // (subBeatIndex 0) are unaffected.
      const eventTime = getSubBeatEventTime(
        currentTime,
        event.subBeatIndex,
        sixteenthSec,
        effectiveParams.swing,
      );
      scheduleEvent(
        offlineCtx,
        event,
        eventTime,
        gain,
        drumBus,
        noiseBuffer,
        sampleBuffers,
        padPanL,
        padPanR,
        bellPan,
        {
          pans: dronePans,
          gains: droneGains,
          filters: droneFilters,
          oscs: droneOscs,
          modOscs: droneModOscs,
          curves: droneCurves,
          scheduledLayers: scheduledDroneLayers,
        },
        targetEndTime,
        // ✅ ADD (sidechain): pass the sidechain amount so kick events can
        // duck the tonal bus. scheduleEvent forwards it to scheduleSidechain.
        effectiveParams.sidechainAmount,
        sidechainTracker,
      );
    }

    currentTime += beatSec;
    beatIndex++;

    if (beatIndex % 64 === 0 && onProgress) {
      const pct = 10 + Math.floor((currentTime / targetEndTime) * 35);
      onProgress({ phase: "scheduling", percent: Math.min(44, pct) });
    }
  }

  onProgress?.({ phase: "rendering", percent: 45 });
  const renderedBuffer = await offlineCtx.startRendering();
  onProgress?.({ phase: "encoding", percent: 85 });

  // Trim pre-roll
  const preRollSamples = Math.ceil(PRE_ROLL_SECONDS * SAMPLE_RATE);
  const outputLength = Math.min(
    Math.ceil(durationSeconds * SAMPLE_RATE),
    renderedBuffer.length - preRollSamples,
  );
  const outputBuffer = new AudioBuffer({
    numberOfChannels: 2,
    length: Math.max(1, outputLength),
    sampleRate: SAMPLE_RATE,
  });
  for (let ch = 0; ch < 2; ch++) {
    const src = renderedBuffer.getChannelData(ch);
    const dst = outputBuffer.getChannelData(ch);
    for (let i = 0; i < outputLength; i++) dst[i] = src[i + preRollSamples];
  }

  onProgress?.({ phase: "encoding", percent: 100 });
  return outputBuffer;
}

// ── FIX C4: Slew helper ──────────────────────────────────────────────────────

function getSlewedHz(
  now: number,
  currentHz: number,
  startHz: number | null,
  endHz: number | null,
  startTime: number | null,
  endTime: number | null,
  duration: number,
): number {
  if (
    startHz === null ||
    endHz === null ||
    startTime === null ||
    endTime === null
  ) {
    return currentHz;
  }
  if (now >= endTime) return endHz;
  const progress = (now - startTime) / duration;
  return startHz + (endHz - startHz) * progress;
}

// ── FIX C2: Noise buffer consuming from main state RNG stream ──────────────

function createNoiseBufferFromState(
  ctx: OfflineAudioContext,
  state: EngineState,
): AudioBuffer {
  const buffer = ctx.createBuffer(1, NOISE_BUFFER_SAMPLES, ctx.sampleRate);
  const data = buffer.getChannelData(0);
  for (let i = 0; i < NOISE_BUFFER_SAMPLES; i++) {
    data[i] = mulberry32Next(state) * 2 - 1;
  }
  return buffer;
}

function createNoiseBufferFromSnapshot(
  ctx: OfflineAudioContext,
  seedSnapshot: number,
): AudioBuffer {
  const buffer = ctx.createBuffer(1, NOISE_BUFFER_SAMPLES, ctx.sampleRate);
  const data = buffer.getChannelData(0);
  const localState = { rngState: seedSnapshot };
  for (let i = 0; i < NOISE_BUFFER_SAMPLES; i++) {
    data[i] = mulberry32Next(localState) * 2 - 1;
  }
  return buffer;
}

// ── Event scheduling ─────────────────────────────────────────────────────────

// scheduleDrone's drone-related params are bundled into a single DroneGraph
// object to keep scheduleEvent's signature manageable. The grouping is
// structural — no behaviour change.
interface DroneGraph {
  pans: StereoPannerNode[];
  gains: GainNode[];
  filters: BiquadFilterNode[];
  oscs: Array<OscillatorNode | null>;
  modOscs: Array<OscillatorNode | null>;
  curves: Array<DroneCurveState | null>;
  scheduledLayers: Set<number>;
}

function scheduleEvent(
  ctx: OfflineAudioContext,
  event: MusicalEvent,
  t0: number,
  mainGain: GainNode,
  drumBus: GainNode,
  noiseBuffer: AudioBuffer,
  sampleBuffers: DecodedSampleBank,
  padPanL: StereoPannerNode,
  padPanR: StereoPannerNode,
  bellPan: StereoPannerNode,
  droneGraph: DroneGraph,
  droneStopTime: number,
  // ✅ ADD (sidechain): passed through to scheduleSidechain() on kick
  // events. Optional — undefined/0 leaves the tonal bus untouched.
  sidechainAmount: number | undefined,
  sidechainTracker: SidechainTracker,
): void {
  switch (event.type) {
    case "kick":
      scheduleKick(ctx, t0, event.amp, drumBus);
      // ✅ ADD (tonal-bus duck on kick): schedule the sidechain duck AFTER
      // the kick is scheduled so the duck attack lines up with the kick hit.
      // Ducks `mainGain` (the tonal bus) — NOT `out` (the master) — so the
      // kick itself (routed to drumBus → out) stays at full level.
      scheduleSidechain(mainGain, t0, sidechainAmount, sidechainTracker);
      break;
    case "snare":
      scheduleSnare(
        ctx,
        t0,
        event.amp,
        event.isGhost ?? false,
        drumBus,
        noiseBuffer,
      );
      break;
    case "hihat":
      scheduleHat(
        ctx,
        t0,
        event.amp,
        event.isClosed ?? true,
        drumBus,
        noiseBuffer,
      );
      break;
    case "drone":
      scheduleDrone(ctx, event, t0, droneStopTime, droneGraph);
      break;
    case "sample":
      scheduleSample(ctx, event, t0, mainGain, sampleBuffers);
      break;
    case "melody":
    case "pad":
    case "bass":
    case "bell":
      scheduleTonal(ctx, event, t0, mainGain, padPanL, padPanR, bellPan);
      break;
  }
}

function scheduleSample(
  ctx: OfflineAudioContext,
  event: MusicalEvent,
  t0: number,
  mainGain: AudioNode,
  sampleBuffers: DecodedSampleBank,
): void {
  const buffer = getDecodedSampleBuffer(sampleBuffers, event.sampleId);
  // ponytail: missing/pending/failed sample buffers are skipped, not queued;
  // upgrading means a real async sample state machine with retry/backfill policy.
  if (!buffer || event.amp <= 0) return;

  scheduleSamplePlayback(
    ctx,
    buffer,
    event.amp,
    event.pan,
    t0,
    mainGain,
    SAMPLE_FADE_SEC,
  );
}

// ── Sidechain automation ────────────────────────────────────────────────────

/**
 * Interpolates the true tonal-bus gain value at `t0` from the attack/release
 * segments recorded by the most recent scheduleSidechain() call. Three
 * branches mirror evaluateDroneEnvelope's piecewise structure:
 *   1. before the attack end: interpolate attackStartV → attackEndV
 *   2. before the release end: interpolate attackEndV → releaseEndV
 *   3. at/after the release end: releaseEndV
 */
function evaluateSidechain(tracker: SidechainTracker, t0: number): number {
  if (t0 < tracker.attackEndT) {
    const span = tracker.attackEndT - tracker.attackStartT;
    if (span <= 0) return tracker.attackEndV;
    const progress = (t0 - tracker.attackStartT) / span;
    return (
      tracker.attackStartV +
      (tracker.attackEndV - tracker.attackStartV) * progress
    );
  }
  if (t0 < tracker.releaseEndT) {
    const span = tracker.releaseEndT - tracker.attackEndT;
    if (span <= 0) return tracker.releaseEndV;
    const progress = (t0 - tracker.attackEndT) / span;
    return (
      tracker.attackEndV + (tracker.releaseEndV - tracker.attackEndV) * progress
    );
  }
  return tracker.releaseEndV;
}

/**
 * ✅ ADD (tonal-bus sidechain duck): Mirrors LiveEngine.applySidechain() for
 * the offline render path. Computes the duck shape via
 * getSidechainDuckShape() (pure, shell-side helper from ./scheduling) and
 * applies a 3-segment gain automation on `mainGain.gain` (the tonal bus).
 *
 * cancelAndHold() anchors to the interpolated mid-ramp value derived from
 * `tracker`, so an overlapping kick continues smoothly from wherever the
 * previous duck currently is instead of jumping. On engines with native
 * cancelAndHoldAtTime the tracker value is ignored in favour of the true
 * held value.
 *
 * No-op when sidechainAmount is undefined or 0 (getSidechainDuckShape
 * returns null in that case).
 */
function scheduleSidechain(
  mainGain: GainNode,
  t0: number,
  sidechainAmount: number | undefined,
  tracker: SidechainTracker,
): void {
  const shape = getSidechainDuckShape(t0, sidechainAmount);
  if (!shape) return;

  const param = mainGain.gain;
  const duckValue = TONAL_BUS_GAIN * shape.duckGainMultiplier;

  const anchorValue = evaluateSidechain(tracker, t0);
  cancelAndHold(param, t0, anchorValue);

  param.linearRampToValueAtTime(duckValue, shape.attackTime);
  param.linearRampToValueAtTime(TONAL_BUS_GAIN, shape.releaseTime);

  tracker.attackStartT = t0;
  tracker.attackStartV = anchorValue;
  tracker.attackEndT = shape.attackTime;
  tracker.attackEndV = duckValue;
  tracker.releaseEndT = shape.releaseTime;
  tracker.releaseEndV = TONAL_BUS_GAIN;
}

// ── Tonal synthesis ─────────────────────────────────────────────────────────

function scheduleDrone(
  ctx: OfflineAudioContext,
  event: MusicalEvent,
  t0: number,
  stopTime: number,
  droneGraph: DroneGraph,
): void {
  if (event.hz === undefined) return;
  const layerIndex = event.droneLayerIndex ?? 0;
  if (layerIndex < 0 || layerIndex >= MAX_DRONE_LAYERS) return;

  const pan = droneGraph.pans[layerIndex];
  const gain = droneGraph.gains[layerIndex];
  const filter = droneGraph.filters[layerIndex];
  const gainParam = gain.gain;

  // Re-anchor the gain envelope to the true automated value at t0, evaluated
  // from the piecewise curve tracked on the previous beat. On engines with
  // native cancelAndHoldAtTime the fallback value is ignored; on the Firefox
  // fallback it prevents a jump-to-zero or jump-to-stale-target.
  const curve = droneGraph.curves[layerIndex];
  let fallbackValue = 0;
  if (curve) {
    fallbackValue = evaluateDroneEnvelope(
      curve.fromValue,
      curve.toValue,
      curve.startTime,
      curve.timeConstant,
      curve.sustainTime,
      curve.sustainValue,
      curve.releaseEndTime,
      curve.releaseTarget,
      t0,
    );
  }
  cancelAndHold(gainParam, t0, fallbackValue);

  pan.pan.setTargetAtTime(event.pan, t0, DRONE_PAN_TIME_CONSTANT_SEC);
  filter.frequency.setTargetAtTime(
    DRONE_FILTER_CUTOFF_HZ,
    t0,
    DRONE_PARAMETER_TIME_CONSTANT_SEC,
  );

  if (!droneGraph.scheduledLayers.has(layerIndex)) {
    const [osc, modOsc] = createOscillator(
      ctx,
      event.hz,
      event.timbre ?? "sine",
    );
    osc.detune.setValueAtTime(event.detuneCents ?? 0, t0);
    osc.connect(filter);

    if (event.sweepSec) {
      // ponytail: naive sine filter sweep only; upgrading means a real
      // per-layer modulation matrix shared by live and offline renderers.
      const lfo = ctx.createOscillator();
      const lfoGain = ctx.createGain();
      lfo.frequency.value = 1 / event.sweepSec;
      lfoGain.gain.value = DRONE_FILTER_LFO_DEPTH_HZ;
      lfo.connect(lfoGain).connect(filter.frequency);
      lfo.start(t0);
      lfo.stop(stopTime + DRONE_TAIL_SEC);
    }

    if (modOsc) {
      modOsc.start(t0);
      modOsc.stop(stopTime + DRONE_TAIL_SEC);
      droneGraph.modOscs[layerIndex] = modOsc;
    }
    osc.start(t0);
    osc.stop(stopTime + DRONE_TAIL_SEC);
    droneGraph.oscs[layerIndex] = osc;
    droneGraph.scheduledLayers.add(layerIndex);
  } else {
    const osc = droneGraph.oscs[layerIndex];
    if (osc) {
      osc.frequency.setTargetAtTime(
        event.hz,
        t0,
        DRONE_PARAMETER_TIME_CONSTANT_SEC,
      );
      osc.detune.setTargetAtTime(
        event.detuneCents ?? 0,
        t0,
        DRONE_PARAMETER_TIME_CONSTANT_SEC,
      );
    }
    const modOsc = droneGraph.modOscs[layerIndex];
    if (modOsc) {
      modOsc.frequency.setTargetAtTime(
        event.hz * FM_MOD_RATIO,
        t0,
        DRONE_PARAMETER_TIME_CONSTANT_SEC,
      );
      // ponytail: this update only adjusts the modulator's *frequency*. The
      // FM mod index (depth) is NOT re-scaled here because the per-layer
      // modGain node isn't retained. Upgrading means storing modGain nodes
      // alongside droneModOscs and scaling them in lockstep with the carrier
      // frequency so the index tracks freq changes too.
    }
  }

  const timeConstant = DRONE_FADE_SEC / DRONE_FADE_TARGET_DIVISOR;
  gainParam.setTargetAtTime(event.amp, t0, timeConstant);

  // Sustain point then release ramp. When the drone's lifespan is shorter
  // than DRONE_FADE_SEC the sustain would land at/after stopTime, so omit
  // it. Per spec the LinearRamp then REPLACES the SetTarget approach — the
  // rendered curve is a straight line from the anchored value at t0 to the
  // release target at stopTime, which evaluateDroneEnvelope's null-sustain
  // branch models exactly.
  const sustainTime = Math.max(t0 + DRONE_FADE_SEC, stopTime - DRONE_FADE_SEC);
  if (sustainTime < stopTime) {
    gainParam.setValueAtTime(event.amp, sustainTime);
  }
  gainParam.linearRampToValueAtTime(DRONE_RELEASE_SILENCE_GAIN, stopTime);

  droneGraph.curves[layerIndex] = {
    fromValue: fallbackValue,
    toValue: event.amp,
    startTime: t0,
    timeConstant: timeConstant,
    sustainTime: sustainTime < stopTime ? sustainTime : null,
    sustainValue: event.amp,
    releaseEndTime: stopTime,
    releaseTarget: DRONE_RELEASE_SILENCE_GAIN,
  };
}

function scheduleTonal(
  ctx: OfflineAudioContext,
  event: MusicalEvent,
  t0: number,
  mainGain: GainNode,
  padPanL: StereoPannerNode,
  padPanR: StereoPannerNode,
  bellPan: StereoPannerNode,
): void {
  const { hz, amp, durationSec, pan, timbre, type } = event;
  if (hz === undefined) return;

  const { env, vibratoAmount } = resolveToneEnvelope(type, pan);

  const [osc, modOsc] = createOscillator(ctx, hz, timbre ?? "sine");
  const g = ctx.createGain();

  let filterNode: BiquadFilterNode | null = null;
  if (timbre === "softsq") {
    filterNode = ctx.createBiquadFilter();
    filterNode.type = "lowpass";
    filterNode.frequency.value = 3200;
    filterNode.Q.value = 0.7;
  }

  if (vibratoAmount) {
    const lfo = ctx.createOscillator();
    const lfoGain = ctx.createGain();
    lfo.frequency.value = 4.5;
    lfoGain.gain.value = vibratoAmount;
    lfo.connect(lfoGain).connect(osc.frequency);
    lfo.start(t0);
    lfo.stop(t0 + durationSec + env.r + 0.05);
  }

  g.gain.setValueAtTime(0, t0);
  g.gain.linearRampToValueAtTime(amp, t0 + env.a);
  g.gain.linearRampToValueAtTime(amp * env.s, t0 + env.a + env.d);
  g.gain.setValueAtTime(amp * env.s, t0 + Math.max(env.a + env.d, durationSec));
  g.gain.linearRampToValueAtTime(
    0.0001,
    t0 + Math.max(env.a + env.d, durationSec) + env.r,
  );

  if (filterNode) {
    osc.connect(filterNode);
    filterNode.connect(g);
  } else {
    osc.connect(g);
  }

  let destination: AudioNode;
  if (type === "pad" && pan < 0) destination = padPanL;
  else if (type === "pad" && pan > 0) destination = padPanR;
  else if (type === "bell") destination = bellPan;
  else destination = mainGain;

  g.connect(destination);

  const stopTime = t0 + Math.max(env.a + env.d, durationSec) + env.r + 0.05;
  if (modOsc) {
    modOsc.start(t0);
    modOsc.stop(stopTime);
  }
  osc.start(t0);
  osc.stop(stopTime);
}

function createOscillator(
  ctx: OfflineAudioContext,
  freq: number,
  timbre: TimbreMode,
): [OscillatorNode, OscillatorNode | null] {
  const osc = ctx.createOscillator();
  let modOsc: OscillatorNode | null = null;
  switch (timbre) {
    case "sine":
      osc.type = "sine";
      break;
    case "triangle":
      osc.type = "triangle";
      break;
    case "softsq":
      osc.type = "square";
      break;
    case "fm": {
      osc.type = "sine";
      modOsc = ctx.createOscillator();
      const modGain = ctx.createGain();
      modOsc.frequency.value = freq * FM_MOD_RATIO;
      modGain.gain.value = freq * FM_INDEX;
      modOsc.connect(modGain).connect(osc.frequency);
      break;
    }
  }
  osc.frequency.value = freq;
  return [osc, modOsc];
}

// ── Drum synthesis ───────────────────────────────────────────────────────────

function scheduleKick(
  ctx: OfflineAudioContext,
  t0: number,
  amp: number,
  drumBus: AudioNode,
): void {
  const osc = ctx.createOscillator();
  const g = ctx.createGain();
  osc.type = "sine";
  osc.frequency.setValueAtTime(150, t0);
  osc.frequency.exponentialRampToValueAtTime(40, t0 + 0.05);
  g.gain.setValueAtTime(amp, t0);
  g.gain.exponentialRampToValueAtTime(0.001, t0 + 0.3);
  osc.connect(g);
  g.connect(drumBus);
  osc.start(t0);
  osc.stop(t0 + 0.3);
}

function scheduleSnare(
  ctx: OfflineAudioContext,
  t0: number,
  amp: number,
  isGhost: boolean,
  drumBus: AudioNode,
  nb: AudioBuffer,
): void {
  const noise = ctx.createBufferSource();
  const filter = ctx.createBiquadFilter();
  const g = ctx.createGain();
  noise.buffer = nb;
  filter.type = "bandpass";
  filter.frequency.value = 2000;
  filter.Q.value = 1.5;
  const dur = isGhost ? 0.06 : 0.12;
  g.gain.setValueAtTime(amp, t0);
  g.gain.exponentialRampToValueAtTime(0.001, t0 + dur);
  noise.connect(filter);
  filter.connect(g);
  g.connect(drumBus);
  noise.start(t0);
  noise.stop(t0 + dur);
}

function scheduleHat(
  ctx: OfflineAudioContext,
  t0: number,
  amp: number,
  closed: boolean,
  drumBus: AudioNode,
  nb: AudioBuffer,
): void {
  const noise = ctx.createBufferSource();
  const filter = ctx.createBiquadFilter();
  const g = ctx.createGain();
  noise.buffer = nb;
  filter.type = "highpass";
  filter.frequency.value = 7000;
  filter.Q.value = 1.0;
  const dur = closed ? 0.03 : 0.08;
  g.gain.setValueAtTime(amp, t0);
  g.gain.exponentialRampToValueAtTime(0.001, t0 + dur);
  noise.connect(filter);
  filter.connect(g);
  g.connect(drumBus);
  noise.start(t0);
  noise.stop(t0 + dur);
}

// ── WAV encoding ──────────────────────────────────────────────────────────────

export function audioBufferToWav(buffer: AudioBuffer): Blob {
  const numChannels = buffer.numberOfChannels;
  const sampleRate = buffer.sampleRate;
  const bytesPerSample = 2;
  const blockAlign = numChannels * bytesPerSample;
  const dataLength = buffer.length * blockAlign;
  const ab = new ArrayBuffer(44 + dataLength);
  const view = new DataView(ab);
  const ws = (o: number, s: string) => {
    for (let i = 0; i < s.length; i++) view.setUint8(o + i, s.charCodeAt(i));
  };
  ws(0, "RIFF");
  view.setUint32(4, 36 + dataLength, true);
  ws(8, "WAVE");
  ws(12, "fmt ");
  view.setUint32(16, 16, true);
  view.setUint16(20, 1, true);
  view.setUint16(22, numChannels, true);
  view.setUint32(24, sampleRate, true);
  view.setUint32(28, sampleRate * blockAlign, true);
  view.setUint16(32, blockAlign, true);
  view.setUint16(34, 16, true);
  ws(36, "data");
  view.setUint32(40, dataLength, true);
  const channels = Array.from({ length: numChannels }, (_, i) =>
    buffer.getChannelData(i),
  );
  let offset = 44;
  for (let i = 0; i < buffer.length; i++) {
    for (let ch = 0; ch < numChannels; ch++) {
      const s = Math.max(-1, Math.min(1, channels[ch][i]));
      view.setInt16(offset, s < 0 ? s * 0x8000 : s * 0x7fff, true);
      offset += 2;
    }
  }
  return new Blob([ab], { type: "audio/wav" });
}

export async function renderAndDownloadWav(
  params: EngineParams,
  durationSeconds: number,
  filename = "ambient_generation.wav",
  startState?: EngineState,
  onProgress?: (p: RenderProgress) => void,
): Promise<void> {
  const buf = await renderAmbient(
    params,
    durationSeconds,
    startState,
    onProgress,
  );
  const url = URL.createObjectURL(audioBufferToWav(buf));
  const a = Object.assign(document.createElement("a"), {
    href: url,
    download: filename,
  });
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 5000);
}
