/**
 * renderAmbient.ts — Offline browser renderer for WAV export.
 *
 * Fixes applied:
 *   C1: Drum events scheduled at beatTime + (subBeatIndex * sixteenthSec)
 *   C2: Noise buffer generated by consuming from state.rngState directly
 *       (advances main stream by ~22k calls, matching original engine.ts order)
 *   C4: 600ms harmonic slew applied via OfflineAudioContext time scheduling
 *   W3: Remove duplicated scene interpolation — accumulate beat time using
 *       actual per-beat BPM from nextState after each getMusicalEvents call
 */

import {
  type EngineParams,
  type EngineState,
  type MusicalEvent,
  type TimbreMode,
  getMusicalEvents,
  createInitialState,
  initializeBell,
  mulberry32Next,
  getEffectiveSceneParams,
} from "./musicalLogic";

const FM_MOD_RATIO = 1.5;
const FM_INDEX = 1.8;

const ADSR_MELODY = { a: 0.02, d: 0.2, s: 0.55, r: 0.25 };
const ADSR_PAD_L = { a: 0.5, d: 0.8, s: 0.7, r: 0.8 };
const ADSR_PAD_R = { a: 0.6, d: 0.8, s: 0.7, r: 0.9 };
const ADSR_BASS = { a: 0.005, d: 0.15, s: 0.25, r: 0.2 };
const ADSR_BELL = { a: 0.01, d: 0.1, s: 0.2, r: 0.15 };

export interface RenderProgress {
  phase: "preparing" | "scheduling" | "rendering" | "encoding";
  percent: number;
}

export async function renderAmbient(
  params: EngineParams,
  durationSeconds: number,
  startState?: EngineState,
  onProgress?: (progress: RenderProgress) => void,
): Promise<AudioBuffer> {
  const SAMPLE_RATE = 44100;
  const effectiveBpm = params.bpm || 72;
  const PRE_ROLL_SECONDS = 4 * (60 / effectiveBpm) * 4; // 4 bars

  // Over-allocate 10% — we trim to exact duration after rendering
  const totalSecondsEstimate = (PRE_ROLL_SECONDS + durationSeconds) * 1.1;
  const totalSamples = Math.ceil(SAMPLE_RATE * totalSecondsEstimate);

  onProgress?.({ phase: "preparing", percent: 5 });

  const offlineCtx = new OfflineAudioContext(2, totalSamples, SAMPLE_RATE);

  // ── Audio graph (identical to LiveEngine) ──
  const gain = offlineCtx.createGain();
  const delay = offlineCtx.createDelay(2.0);
  const fb = offlineCtx.createGain();
  const filter = offlineCtx.createBiquadFilter();
  const out = offlineCtx.createGain();

  gain.gain.value = 0.3;
  delay.delayTime.value = 0.3 + 0.4 * (params.mix || 0.4);
  fb.gain.value = 0.2 + 0.5 * (params.mix || 0.4);
  filter.type = "lowpass";
  filter.frequency.value = 5000 + (params.mix || 0.4) * 4000;
  filter.Q.value = 1.0;

  gain.connect(filter);
  filter.connect(delay);
  delay.connect(fb);
  fb.connect(delay);
  delay.connect(out);
  filter.connect(out);
  out.connect(offlineCtx.destination);

  const drumBus = offlineCtx.createGain();
  const drumCompressor = offlineCtx.createDynamicsCompressor();
  drumCompressor.threshold.value = -20;
  drumCompressor.ratio.value = 3;
  drumCompressor.attack.value = 0.003;
  drumCompressor.release.value = 0.25;
  drumBus.connect(drumCompressor);
  drumCompressor.connect(out);

  // FIX W3: Persistent panners in offline context too
  const padPanL = offlineCtx.createStereoPanner();
  const padPanR = offlineCtx.createStereoPanner();
  const bellPan = offlineCtx.createStereoPanner();
  padPanL.pan.value = 0;
  padPanR.pan.value = 0;
  bellPan.pan.value = 0;
  padPanL.connect(gain);
  padPanR.connect(gain);
  bellPan.connect(gain);

  onProgress?.({ phase: "scheduling", percent: 10 });

  // ── RNG init order matches original engine.ts constructor exactly ──
  // Original order: mulberry32(seed) → createNoiseBuffer() [~22k calls] → nextBellBeat [1 call]
  //
  // FRESH export (no startState):
  //   createInitialState → createNoiseBufferFromState [~22k] → initializeBell [1]
  //   This matches the original constructor RNG order exactly.
  //
  // LIVE-EXPORT (startState provided from running LiveEngine):
  //   The RNG stream is already past noise buffer and bell init.
  //   Do NOT call createNoiseBufferFromState — that would advance ~22k extra calls
  //   and desync the export from the live stream.
  //   Generate a fresh noise buffer from a separate RNG snapshot instead.
  let state: EngineState;
  let noiseBuffer: AudioBuffer;

  if (startState) {
    // Continuing from live engine — RNG already positioned past noise buffer
    state = { ...startState };
    // Generate noise buffer from a snapshot of current rngState so we don't
    // advance the main stream (drum texture will match this session's noise)
    noiseBuffer = createNoiseBufferFromSnapshot(offlineCtx, state.rngState);
  } else {
    // Fresh render — match original constructor order exactly
    state = createInitialState(params);
    noiseBuffer = createNoiseBufferFromState(offlineCtx, state); // advances ~22k in main stream
    state = initializeBell(state); // advances 1 in main stream
  }

  // FIX C4: Harmonic slew tracking for offline context
  let slewStartHz: number | null = null;
  let slewEndHz: number | null = null;
  let slewStartTime: number | null = null;
  let slewEndTime: number | null = null;
  const SLEW_DURATION = 0.6;

  // ── FIX W3 + beat timing: accumulate time from actual per-beat BPM ──
  // Instead of duplicating scene interpolation logic, we read the BPM that
  // was actually used in each beat from the state returned by getMusicalEvents.
  // The effective BPM for beat i is reflected in: 60 / effectiveBpmAtBeat
  // We compute this from the scene state in nextState after each call.

  let currentTime = 0;
  const targetEndTime = PRE_ROLL_SECONDS + durationSeconds;
  const maxBeats = Math.ceil(totalSecondsEstimate * (effectiveBpm / 60)) + 20;
  let beatIndex = 0;

  while (currentTime < targetEndTime && beatIndex < maxBeats) {
    // FIX: Compute slewed root BEFORE getMusicalEvents — matches original engine.ts
    // which ran updateHarmonicLoop() before noteHz() calls within the same tick.
    const slewedRootHz = getSlewedHz(
      currentTime,
      state.currentRootHz,
      slewStartHz,
      slewEndHz,
      slewStartTime,
      slewEndTime,
      SLEW_DURATION,
    );
    state = { ...state, currentRootHz: slewedRootHz };

    const prevTargetRootHz = state.targetRootHz;

    // FIX: compute effective BPM/mix from current state BEFORE the event call
    const preBeatParams = getEffectiveSceneParams(state, params);
    const beatSec = 60 / preBeatParams.bpm;
    params.bpm = preBeatParams.bpm;
    const sceneMix = preBeatParams.mix;
    const sixteenthSec = beatSec / 4;

    const { events, nextState } = getMusicalEvents(
      state.beat,
      { ...state },
      params,
    );
    state = nextState;

    // FIX C4: Detect harmonic change — start slew for upcoming beats
    if (state.targetRootHz !== prevTargetRootHz) {
      slewStartHz = slewedRootHz; // start from already-slewed position
      slewEndHz = state.targetRootHz;
      slewStartTime = currentTime;
      slewEndTime = currentTime + SLEW_DURATION;
    }

    // Update persistent panner values at this beat time
    const panValue = Math.sin(state.panDriftPhase) * 0.1;
    padPanL.pan.setValueAtTime(-panValue, currentTime);
    padPanR.pan.setValueAtTime(panValue, currentTime);
    bellPan.pan.setValueAtTime(
      Math.sin(state.panDriftPhase * 1.3) * 0.15,
      currentTime,
    );

    // Animate scene mix each beat — matches original updateSceneEngine setMix() call.
    delay.delayTime.setValueAtTime(0.3 + 0.4 * sceneMix, currentTime);
    fb.gain.setValueAtTime(0.2 + 0.5 * sceneMix, currentTime);
    filter.frequency.setValueAtTime(5000 + sceneMix * 4000, currentTime);

    for (const event of events) {
      // FIX C1: schedule drum events with sub-beat offset
      const eventTime = currentTime + event.subBeatIndex * sixteenthSec;
      scheduleEvent(
        offlineCtx,
        event,
        eventTime,
        gain,
        drumBus,
        noiseBuffer,
        padPanL,
        padPanR,
        bellPan,
      );
    }

    currentTime += beatSec;
    beatIndex++;

    if (beatIndex % 64 === 0 && onProgress) {
      const pct = 10 + Math.floor((currentTime / targetEndTime) * 35);
      onProgress({ phase: "scheduling", percent: Math.min(44, pct) });
    }
  }

  onProgress?.({ phase: "rendering", percent: 45 });
  const renderedBuffer = await offlineCtx.startRendering();
  onProgress?.({ phase: "encoding", percent: 85 });

  // Trim pre-roll
  const preRollSamples = Math.ceil(PRE_ROLL_SECONDS * SAMPLE_RATE);
  const outputLength = Math.min(
    Math.ceil(durationSeconds * SAMPLE_RATE),
    renderedBuffer.length - preRollSamples,
  );
  const outputBuffer = new AudioBuffer({
    numberOfChannels: 2,
    length: Math.max(1, outputLength),
    sampleRate: SAMPLE_RATE,
  });
  for (let ch = 0; ch < 2; ch++) {
    const src = renderedBuffer.getChannelData(ch);
    const dst = outputBuffer.getChannelData(ch);
    for (let i = 0; i < outputLength; i++) dst[i] = src[i + preRollSamples];
  }

  onProgress?.({ phase: "encoding", percent: 100 });
  return outputBuffer;
}

// ── FIX C4: Slew helper for offline context ───────────────────────────────────

function getSlewedHz(
  now: number,
  currentHz: number,
  startHz: number | null,
  endHz: number | null,
  startTime: number | null,
  endTime: number | null,
  duration: number,
): number {
  if (
    startHz === null ||
    endHz === null ||
    startTime === null ||
    endTime === null
  ) {
    return currentHz;
  }
  if (now >= endTime) return endHz;
  const progress = (now - startTime) / duration;
  return startHz + (endHz - startHz) * progress;
}

// ── FIX C2: Noise buffer consuming from main state RNG stream ─────────────────
// Used for fresh renders — advances state.rngState by ~22k calls in-place.

function createNoiseBufferFromState(
  ctx: OfflineAudioContext,
  state: EngineState,
): AudioBuffer {
  const bufferSize = Math.floor(ctx.sampleRate * 0.5); // 22050 at 44100Hz
  const buffer = ctx.createBuffer(1, bufferSize, ctx.sampleRate);
  const data = buffer.getChannelData(0);
  // Consume directly from state.rngState — advances the main stream
  for (let i = 0; i < bufferSize; i++) {
    data[i] = mulberry32Next(state) * 2 - 1;
  }
  return buffer;
}

// Used for live-export — generates from a snapshot so main stream is NOT advanced.
function createNoiseBufferFromSnapshot(
  ctx: OfflineAudioContext,
  seedSnapshot: number,
): AudioBuffer {
  const bufferSize = Math.floor(ctx.sampleRate * 0.5);
  const buffer = ctx.createBuffer(1, bufferSize, ctx.sampleRate);
  const data = buffer.getChannelData(0);
  const localState = { rngState: seedSnapshot };
  for (let i = 0; i < bufferSize; i++) {
    data[i] = mulberry32Next(localState) * 2 - 1;
  }
  return buffer;
}

// ── Event scheduling ──────────────────────────────────────────────────────────

function scheduleEvent(
  ctx: OfflineAudioContext,
  event: MusicalEvent,
  t0: number,
  mainGain: GainNode,
  drumBus: GainNode,
  noiseBuffer: AudioBuffer,
  padPanL: StereoPannerNode,
  padPanR: StereoPannerNode,
  bellPan: StereoPannerNode,
): void {
  switch (event.type) {
    case "kick":
      scheduleKick(ctx, t0, event.amp, drumBus);
      break;
    case "snare":
      scheduleSnare(
        ctx,
        t0,
        event.amp,
        event.isGhost ?? false,
        drumBus,
        noiseBuffer,
      );
      break;
    case "hihat":
      scheduleHat(
        ctx,
        t0,
        event.amp,
        event.isClosed ?? true,
        drumBus,
        noiseBuffer,
      );
      break;
    case "melody":
    case "pad":
    case "bass":
    case "bell":
      scheduleTonal(ctx, event, t0, mainGain, padPanL, padPanR, bellPan);
      break;
  }
}

// ── Tonal synthesis ───────────────────────────────────────────────────────────

function scheduleTonal(
  ctx: OfflineAudioContext,
  event: MusicalEvent,
  t0: number,
  mainGain: GainNode,
  padPanL: StereoPannerNode,
  padPanR: StereoPannerNode,
  bellPan: StereoPannerNode,
): void {
  const { hz, amp, durationSec, pan, timbre, type } = event;
  if (hz === undefined) return;

  let env: { a: number; d: number; s: number; r: number };
  let vibratoAmount: number | undefined;

  switch (type) {
    case "melody":
      env = ADSR_MELODY;
      vibratoAmount = 1.5;
      break;
    case "pad":
      env = pan < 0 ? ADSR_PAD_L : ADSR_PAD_R;
      break;
    case "bass":
      env = ADSR_BASS;
      break;
    case "bell":
      env = ADSR_BELL;
      break;
    default:
      env = ADSR_PAD_L;
  }

  const [osc, modOsc] = createOscillator(ctx, hz, timbre ?? "sine");
  const g = ctx.createGain();

  let filterNode: BiquadFilterNode | null = null;
  if (timbre === "softsq") {
    filterNode = ctx.createBiquadFilter();
    filterNode.type = "lowpass";
    filterNode.frequency.value = 3200;
    filterNode.Q.value = 0.7;
  }

  if (vibratoAmount) {
    const lfo = ctx.createOscillator();
    const lfoGain = ctx.createGain();
    lfo.frequency.value = 4.5;
    lfoGain.gain.value = vibratoAmount;
    lfo.connect(lfoGain).connect(osc.frequency);
    lfo.start(t0);
    lfo.stop(t0 + durationSec + env.r + 0.05);
  }

  g.gain.setValueAtTime(0, t0);
  g.gain.linearRampToValueAtTime(amp, t0 + env.a);
  g.gain.linearRampToValueAtTime(amp * env.s, t0 + env.a + env.d);
  g.gain.setValueAtTime(amp * env.s, t0 + Math.max(env.a + env.d, durationSec));
  g.gain.linearRampToValueAtTime(
    0.0001,
    t0 + Math.max(env.a + env.d, durationSec) + env.r,
  );

  if (filterNode) {
    osc.connect(filterNode);
    filterNode.connect(g);
  } else {
    osc.connect(g);
  }

  // FIX W1/W3: Route to same persistent panner nodes as LiveEngine
  let destination: AudioNode;
  if (type === "pad" && pan < 0) destination = padPanL;
  else if (type === "pad" && pan > 0) destination = padPanR;
  else if (type === "bell") destination = bellPan;
  else destination = mainGain;

  g.connect(destination);

  const stopTime = t0 + Math.max(env.a + env.d, durationSec) + env.r + 0.05;
  if (modOsc) {
    modOsc.start(t0);
    modOsc.stop(stopTime);
  }
  osc.start(t0);
  osc.stop(stopTime);
}

function createOscillator(
  ctx: OfflineAudioContext,
  freq: number,
  timbre: TimbreMode,
): [OscillatorNode, OscillatorNode | null] {
  const osc = ctx.createOscillator();
  let modOsc: OscillatorNode | null = null;
  switch (timbre) {
    case "sine":
      osc.type = "sine";
      break;
    case "triangle":
      osc.type = "triangle";
      break;
    case "softsq":
      osc.type = "square";
      break;
    case "fm": {
      osc.type = "sine";
      modOsc = ctx.createOscillator();
      const modGain = ctx.createGain();
      modOsc.frequency.value = freq * FM_MOD_RATIO;
      modGain.gain.value = freq * FM_INDEX;
      modOsc.connect(modGain).connect(osc.frequency);
      break;
    }
  }
  osc.frequency.value = freq;
  return [osc, modOsc];
}

// ── Drum synthesis ────────────────────────────────────────────────────────────

function scheduleKick(
  ctx: OfflineAudioContext,
  t0: number,
  amp: number,
  drumBus: AudioNode,
): void {
  const osc = ctx.createOscillator();
  const g = ctx.createGain();
  osc.type = "sine";
  osc.frequency.setValueAtTime(150, t0);
  osc.frequency.exponentialRampToValueAtTime(40, t0 + 0.05);
  g.gain.setValueAtTime(amp, t0);
  g.gain.exponentialRampToValueAtTime(0.001, t0 + 0.3);
  osc.connect(g);
  g.connect(drumBus);
  osc.start(t0);
  osc.stop(t0 + 0.3);
}

function scheduleSnare(
  ctx: OfflineAudioContext,
  t0: number,
  amp: number,
  isGhost: boolean,
  drumBus: AudioNode,
  nb: AudioBuffer,
): void {
  const noise = ctx.createBufferSource();
  const filter = ctx.createBiquadFilter();
  const g = ctx.createGain();
  noise.buffer = nb;
  filter.type = "bandpass";
  filter.frequency.value = 2000;
  filter.Q.value = 1.5;
  const dur = isGhost ? 0.06 : 0.12;
  g.gain.setValueAtTime(amp, t0);
  g.gain.exponentialRampToValueAtTime(0.001, t0 + dur);
  noise.connect(filter);
  filter.connect(g);
  g.connect(drumBus);
  noise.start(t0);
  noise.stop(t0 + dur);
}

function scheduleHat(
  ctx: OfflineAudioContext,
  t0: number,
  amp: number,
  closed: boolean,
  drumBus: AudioNode,
  nb: AudioBuffer,
): void {
  const noise = ctx.createBufferSource();
  const filter = ctx.createBiquadFilter();
  const g = ctx.createGain();
  noise.buffer = nb;
  filter.type = "highpass";
  filter.frequency.value = 7000;
  filter.Q.value = 1.0;
  const dur = closed ? 0.03 : 0.08;
  g.gain.setValueAtTime(amp, t0);
  g.gain.exponentialRampToValueAtTime(0.001, t0 + dur);
  noise.connect(filter);
  filter.connect(g);
  g.connect(drumBus);
  noise.start(t0);
  noise.stop(t0 + dur);
}

// ── WAV encoding ──────────────────────────────────────────────────────────────

export function audioBufferToWav(buffer: AudioBuffer): Blob {
  const numChannels = buffer.numberOfChannels;
  const sampleRate = buffer.sampleRate;
  const bytesPerSample = 2;
  const blockAlign = numChannels * bytesPerSample;
  const dataLength = buffer.length * blockAlign;
  const ab = new ArrayBuffer(44 + dataLength);
  const view = new DataView(ab);
  const ws = (o: number, s: string) => {
    for (let i = 0; i < s.length; i++) view.setUint8(o + i, s.charCodeAt(i));
  };
  ws(0, "RIFF");
  view.setUint32(4, 36 + dataLength, true);
  ws(8, "WAVE");
  ws(12, "fmt ");
  view.setUint32(16, 16, true);
  view.setUint16(20, 1, true);
  view.setUint16(22, numChannels, true);
  view.setUint32(24, sampleRate, true);
  view.setUint32(28, sampleRate * blockAlign, true);
  view.setUint16(32, blockAlign, true);
  view.setUint16(34, 16, true);
  ws(36, "data");
  view.setUint32(40, dataLength, true);
  const channels = Array.from({ length: numChannels }, (_, i) =>
    buffer.getChannelData(i),
  );
  let offset = 44;
  for (let i = 0; i < buffer.length; i++) {
    for (let ch = 0; ch < numChannels; ch++) {
      const s = Math.max(-1, Math.min(1, channels[ch][i]));
      view.setInt16(offset, s < 0 ? s * 0x8000 : s * 0x7fff, true);
      offset += 2;
    }
  }
  return new Blob([ab], { type: "audio/wav" });
}

export async function renderAndDownloadWav(
  params: EngineParams,
  durationSeconds: number,
  filename = "ambient_generation.wav",
  startState?: EngineState,
  onProgress?: (p: RenderProgress) => void,
): Promise<void> {
  const buf = await renderAmbient(
    params,
    durationSeconds,
    startState,
    onProgress,
  );
  const url = URL.createObjectURL(audioBufferToWav(buf));
  const a = Object.assign(document.createElement("a"), {
    href: url,
    download: filename,
  });
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 5000);
}
