/**
 * bench/lib/assets.mjs — deterministic synthetic media for the D ladder.
 * If the user drops real content at bench/assets/bg.png or bench/assets/bg.gif
 * or bench/assets/loop.mp4, those files are used instead (they are the
 * realistic payload); otherwise ffmpeg generates deterministic stand-ins.
 */
import fs from "node:fs";
import path from "node:path";
import { runProcess } from "./ffmpeg.mjs";
import {
  PREFIX_WIDTH, PREFIX_HEIGHT, LOOP_GIF_SEC, LOOP_GIF_FPS, LOOP_GIF_WIDTH, LOOP_GIF_HEIGHT, LOOP_MP4_SEC,
} from "./constants.mjs";

const ASSETS_DIR = path.resolve(import.meta.dirname, "..", "assets");

/** 1920×1080 busy still frame (testsrc2 stresses encoders like a photo; a
 *  flat color would flatter libx264 unrealistically). */
async function ensureStill(outPath) {
  const args = [
    "-y", "-v", "error",
    "-f", "lavfi", "-i", `testsrc2=size=${PREFIX_WIDTH}x${PREFIX_HEIGHT}:rate=1`,
    "-frames:v", "1", outPath,
  ];
  return runProcess("ffmpeg", args);
}

/** 30s@10fps 640×360 animated GIF, palette-accurate (real GIF decode cost). */
async function ensureGif(outPath) {
  const args = [
    "-y", "-v", "error",
    "-f", "lavfi", "-i", `testsrc2=size=${LOOP_GIF_WIDTH}x${LOOP_GIF_HEIGHT}:rate=${LOOP_GIF_FPS}:duration=${LOOP_GIF_SEC}`,
    "-filter_complex", "split[a][b];[a]palettegen[p];[b][p]paletteuse",
    outPath,
  ];
  return runProcess("ffmpeg", args);
}

/** 10s@10fps 640×360 H.264 loop (recommended loop-background format). */
async function ensureLoopMp4(outPath) {
  const args = [
    "-y", "-v", "error",
    "-f", "lavfi", "-i", `testsrc2=size=${LOOP_GIF_WIDTH}x${LOOP_GIF_HEIGHT}:rate=${LOOP_GIF_FPS}:duration=${LOOP_MP4_SEC}`,
    "-c:v", "libx264", "-preset", "veryfast", "-crf", "23",
    "-pix_fmt", "yuv420p",
    outPath,
  ];
  return runProcess("ffmpeg", args);
}

async function ensure(file, generator) {
  const outPath = path.join(ASSETS_DIR, file);
  if (fs.existsSync(outPath) && fs.statSync(outPath).size > 0) {
    return { path: outPath, source: "user-provided" };
  }
  const res = await generator(outPath);
  if (res.code !== 0) return { path: null, source: null, error: res.stderr.slice(-500) };
  return { path: outPath, source: `synthetic (generated by bench: ${file})` };
}

export async function ensureAssets() {
  fs.mkdirSync(ASSETS_DIR, { recursive: true });
  const [still, gif, loopMp4] = await Promise.all([
    ensure("bg.png", ensureStill),
    ensure("bg.gif", ensureGif),
    ensure("loop.mp4", ensureLoopMp4),
  ]);
  return { still, gif, loopMp4 };
}
